apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-puma
  template:
    metadata:
      name: ping-rails
      labels:
        app: rails-puma
    spec:
      containers:
        - name: ping-rails
          image: goromlagche/ping
          ports:
            - containerPort: 3000
          env:
            - name: SECRET_KEY_BASE
              value: "d1f8aed21b72624b6d3ea79c30dc53778cb144586c2a0e7d4f950b7d3ac53b05ddc6db65c9a5cffab91f3201d5fa6232d0d463e0317a81421942a4944d455c4d"
            - name: REDIS_URL
              value: redis://redis-service:6379
